version: 0.2

phases:
  install:
    commands:
      - printenv
      - cd lambda/custom && npm install

  build:
    commands:
      - npm test
      - run build-aws-resource

artifacts:
  files:
    - lambda/custom/ShoppingListAWS.zip
  discard-paths: yes
